import {
  Calendar,
  Mail,
  Phone,
  Instagram,
  Facebook,
  Youtube,
  Star,
  ArrowRight,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  User,
  Clock,
  CheckCircle,
  ExternalLink,
  MessageSquare,
  Sparkles,
  TrendingUp,
  Heart,
} from 'lucide-react';

export const Icons = {
  calendar: Calendar,
  mail: Mail,
  phone: Phone,
  instagram: Instagram,
  facebook: Facebook,
  youtube: Youtube,
  star: Star,
  arrowRight: ArrowRight,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  user: User,
  clock: Clock,
  checkCircle: CheckCircle,
  external: ExternalLink,
  messageSquare: MessageSquare,
  sparkles: Sparkles,
  trendingUp: TrendingUp,
  heart: Heart,
};
